/**:
  ros__parameters:
    # Plugin execution order - plugins will run in this order
    plugin_names:
      - "autoware::trajectory_optimizer::plugin::TrajectoryPointFixer"
      - "autoware::trajectory_optimizer::plugin::TrajectoryKinematicFeasibilityEnforcer"
      - "autoware::trajectory_optimizer::plugin::TrajectoryQPSmoother"
      - "autoware::trajectory_optimizer::plugin::TrajectoryKinematicFeasibilityEnforcer"
      - "autoware::trajectory_optimizer::plugin::TrajectoryEBSmootherOptimizer"
      - "autoware::trajectory_optimizer::plugin::TrajectorySplineSmoother"
      - "autoware::trajectory_optimizer::plugin::TrajectoryVelocityOptimizer"
      - "autoware::trajectory_optimizer::plugin::TrajectoryExtender"

    # Plugin activation flags - control runtime enable/disable
    use_akima_spline_interpolation: true
    use_eb_smoother: false
    use_qp_smoother: true
    fix_invalid_points: true
    optimize_velocity: true
    extend_trajectory_backward: false
    use_kinematic_feasibility_enforcer: true
