/**:
  ros__parameters:
    gyro_bias_threshold: 0.009 # [rad/s]
    timer_callback_interval_sec: 0.1 # [sec]
    diagnostics_updater_interval_sec: 0.1 # [sec]
    straight_motion_ang_vel_upper_limit: 0.015 # [rad/s]
